parameters:
    database_driver:   pdo_mysql
    database_host:     localhost
    database_port:     3308
    database_name:     smartcore2
    database_user:     root
    database_password: root

    mailer_transport:  smtp
    mailer_host:       localhost
    mailer_user:       ~
    mailer_password:   ~

    locale:            en
    secret:            ThisTokenIsNotSoSecretChangeIt
