acme_acme_blog:
#    resource: "@AcmeBlogBundle/Controller/"
#    type:     annotation
    resource: "@AcmeBlogBundle/Resources/config/routing.yml"
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
acme_demo:
    resource: "@AcmeDemoBundle/Resources/config/routing.yml"
    prefix:   /