<?php

namespace Acme\BlogBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class SecurityController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Acme\BlogBundle\Controller\SecurityController();
        return $instance;
    }
}
